on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        # TODO: GitHub actions are not free on private repositories.
        # When this is made public, we should test starting from 1.13.x, and
        # with macos-latest and windows-latest.
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: TestInline
      if: matrix.go-version == '1.16.x' && matrix.os == 'ubuntu-latest'
      run: go test -v -run=TestInline
      env: {TEST_INLINE: true}
    - name: Format
      if: matrix.go-version == '1.16.x' && matrix.os == 'ubuntu-latest'
      run: diff -u <(echo -n) <(gofmt -d .)
